"use client";
/**
 * ImportSheet — three-source coffee import wizard.
 *
 * Sources:
 *   1. Bean Conqueror .json export
 *   2. Generic CSV (generated by an LLM using the prompt from lib/import/prompt.ts)
 *   3. Paste raw text → /api/import (LLM-structured, only when llmEnabled)
 *
 * Phase state machine: source → parsing → review → committing → done
 *
 * On commit: calls importCoffees() from AppContext, which batch-inserts with
 * optimistic prepend + single persist (full rollback on failure).
 */
import { useState, useRef, useCallback } from "react";
import { Sheet } from "@/components/ui/Sheet";
import { SheetHeader } from "@/components/ui/SheetHeader";
import { EmptyState } from "@/components/ui/EmptyState";
import { Icon } from "@/components/ui/Icon";
import { useApp } from "@/lib/store/AppContext";
import { parseBeanConqueror } from "@/lib/import/beanconqueror";
import { parseCsv } from "@/lib/import/csv";
import { markDuplicates } from "@/lib/import/dedup";
import { toCoffee } from "@/lib/import/materialize";
import { IMPORT_PROMPT, CSV_COLUMNS, CSV_EXAMPLE } from "@/lib/import/prompt";
import type { ReviewCoffee } from "@/lib/import/types";
import type { Coffee } from "@/lib/types";

type Source = "bc" | "csv" | "paste";
type Phase = "source" | "parsing" | "review" | "committing" | "done";

interface ImportSheetProps {
  open: boolean;
  onClose: () => void;
}

// ---- Inline field editors for the review step ----

function ReviewRow({
  item,
  included,
  onToggle,
  onChange,
}: {
  item: ReviewCoffee;
  included: boolean;
  onToggle: () => void;
  onChange: (patch: Partial<ReviewCoffee>) => void;
}) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div style={{
      border: `1px solid ${item.isDuplicate ? "var(--accent)" : "var(--line)"}`,
      borderRadius: 13,
      marginBottom: 8,
      background: included ? "var(--surface)" : "var(--surface-muted, var(--surface))",
      opacity: included ? 1 : 0.5,
      overflow: "hidden",
    }}>
      {/* Row summary */}
      <div
        style={{ display: "flex", alignItems: "center", gap: 10, padding: "11px 13px", cursor: "pointer" }}
        onClick={() => setExpanded((v) => !v)}
      >
        {/* Toggle include */}
        <button
          onClick={(e) => { e.stopPropagation(); onToggle(); }}
          aria-label={included ? "Exclude this coffee" : "Include this coffee"}
          style={{
            flexShrink: 0, width: 22, height: 22, borderRadius: 6,
            background: included ? "var(--accent)" : "var(--surface)",
            border: included ? "none" : "1.5px solid var(--ink-faint)",
            display: "flex", alignItems: "center", justifyContent: "center",
            cursor: "pointer",
          }}
        >
          {included && <Icon name="check" size={13} stroke={2.5} style={{ color: "var(--bg)" }} />}
        </button>

        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontWeight: 600, fontSize: 14.5, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
            {item.name || <span style={{ color: "var(--ink-faint)" }}>Untitled</span>}
          </div>
          <div className="label" style={{ color: "var(--ink-faint)" }}>
            {item.roaster}
            {item.origin ? ` · ${item.origin}` : ""}
            {item.roasted_at ? ` · ${item.roasted_at}` : ""}
          </div>
        </div>

        {item.isDuplicate && (
          <span className="chip" style={{ flexShrink: 0, fontSize: 10.5, color: "var(--accent)" }}>
            duplicate
          </span>
        )}

        <Icon
          name="chev"
          size={14}
          stroke={2}
          style={{ color: "var(--ink-faint)", flexShrink: 0, transform: expanded ? "rotate(90deg)" : "none", transition: "transform .15s ease" }}
        />
      </div>

      {/* Expanded editor */}
      {expanded && (
        <div style={{ borderTop: "1px solid var(--line)", padding: "12px 13px" }}>
          {(["roaster", "name", "origin", "region", "varietal", "process", "roast", "roasted_at"] as const).map((field) => (
            <label key={field} style={{ display: "block", marginBottom: 10 }}>
              <div className="label" style={{ marginBottom: 4, color: "var(--ink-faint)" }}>{field.replace(/_/g, " ")}</div>
              <input
                value={(item[field] as string) ?? ""}
                onChange={(e) => onChange({ [field]: e.target.value })}
                style={{
                  width: "100%", padding: "9px 12px", borderRadius: 10,
                  background: "var(--bg)", border: "1px solid var(--line)",
                  color: "var(--ink)", fontFamily: "var(--font-ui)", fontSize: 15,
                  outline: "none", boxSizing: "border-box",
                }}
              />
            </label>
          ))}
          <label style={{ display: "block", marginBottom: 0 }}>
            <div className="label" style={{ marginBottom: 4, color: "var(--ink-faint)" }}>notes (comma-separated)</div>
            <input
              value={(item.notes ?? []).join(", ")}
              onChange={(e) => onChange({ notes: e.target.value.split(",").map((s) => s.trim()).filter(Boolean) })}
              placeholder="cherry, chocolate, caramel"
              style={{
                width: "100%", padding: "9px 12px", borderRadius: 10,
                background: "var(--bg)", border: "1px solid var(--line)",
                color: "var(--ink)", fontFamily: "var(--font-ui)", fontSize: 15,
                outline: "none", boxSizing: "border-box",
              }}
            />
          </label>
        </div>
      )}
    </div>
  );
}

// ---- Main component ----

export function ImportSheet({ open, onClose }: ImportSheetProps) {
  const { coffees, importCoffees, llmEnabled } = useApp();

  const [phase, setPhase] = useState<Phase>("source");
  const [source, setSource] = useState<Source>("bc");
  const [pasteText, setPasteText] = useState("");
  const [parseError, setParseError] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const [rows, setRows] = useState<ReviewCoffee[]>([]);
  const [included, setIncluded] = useState<Set<number>>(new Set());
  const [importedCount, setImportedCount] = useState(0);
  const [promptCopied, setPromptCopied] = useState(false);
  const [showPrompt, setShowPrompt] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  const reset = useCallback(() => {
    setPhase("source");
    setParseError(null);
    setWarnings([]);
    setRows([]);
    setIncluded(new Set());
    setImportedCount(0);
    setPasteText("");
  }, []);

  const handleClose = () => { reset(); onClose(); };

  // ---- File input ----
  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setPhase("parsing");
    setParseError(null);

    const reader = new FileReader();
    reader.onload = (ev) => {
      const text = ev.target?.result as string;
      const isJson = file.name.toLowerCase().endsWith(".json");
      const result = isJson ? parseBeanConqueror(text) : parseCsv(text);

      if (!result.coffees.length) {
        setParseError(result.warnings[0] ?? "No coffees found in file.");
        setPhase("source");
        return;
      }

      const reviewed = markDuplicates(result.coffees, coffees);
      const defaultIncluded = new Set(
        reviewed.map((_, i) => i).filter((i) => !reviewed[i].isDuplicate)
      );
      setRows(reviewed);
      setIncluded(defaultIncluded);
      setWarnings(result.warnings);
      setPhase("review");
    };
    reader.onerror = () => {
      setParseError("Could not read file.");
      setPhase("source");
    };
    reader.readAsText(file);

    // Reset input so the same file can be re-selected after an error
    e.target.value = "";
  };

  // ---- LLM paste ----
  const handleParse = async () => {
    if (!pasteText.trim()) return;
    setPhase("parsing");
    setParseError(null);

    try {
      const res = await fetch("/api/import", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: pasteText }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Import failed");

      // The API returns { coffees: ImportedCoffee[] } directly
      const apiCoffees: import("@/lib/import/types").ImportedCoffee[] = data.coffees ?? [];
      if (!apiCoffees.length) {
        setParseError("No coffees found in the text. Try adding more detail.");
        setPhase("source");
        return;
      }
      const reviewed = markDuplicates(apiCoffees, coffees);
      const defaultIncluded = new Set(
        reviewed.map((_, i) => i).filter((i) => !reviewed[i].isDuplicate)
      );
      setRows(reviewed);
      setIncluded(defaultIncluded);
      setWarnings([]);
      setPhase("review");
    } catch (err) {
      setParseError(err instanceof Error ? err.message : "Unknown error");
      setPhase("source");
    }
  };

  // ---- Review row edits ----
  const updateRow = (i: number, patch: Partial<ReviewCoffee>) => {
    setRows((prev) => prev.map((r, idx) => idx === i ? { ...r, ...patch } : r));
  };
  const toggleRow = (i: number) => {
    setIncluded((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i); else next.add(i);
      return next;
    });
  };
  const toggleAll = () => {
    if (included.size === rows.length) setIncluded(new Set());
    else setIncluded(new Set(rows.map((_, i) => i)));
  };

  // ---- Commit ----
  const handleCommit = async () => {
    const toAdd: Coffee[] = [];
    rows.forEach((r, i) => {
      if (included.has(i)) toAdd.push(toCoffee(r, coffees));
    });
    if (!toAdd.length) { handleClose(); return; }
    setPhase("committing");
    const ok = await importCoffees(toAdd);
    if (ok) {
      setImportedCount(toAdd.length);
      setPhase("done");
    } else {
      // Error banner is shown by AppContext; go back to review
      setPhase("review");
    }
  };

  // ---- Copy prompt ----
  const copyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(IMPORT_PROMPT);
      setPromptCopied(true);
      setTimeout(() => setPromptCopied(false), 2000);
    } catch {
      // fallback: select the textarea
    }
  };

  if (!open) return null;

  return (
    <Sheet open={open} onClose={handleClose}>
      <div className="screen-pad" style={{ paddingTop: 6, minHeight: 400, paddingBottom: 24 }}>

        {/* Source selection */}
        {(phase === "source" || phase === "parsing") && (
          <>
            <SheetHeader title="Import coffees" onClose={handleClose} />

            {parseError && (
              <div style={{
                background: "color-mix(in srgb, var(--bad, #b65f4f) 90%, transparent)",
                color: "#fff", borderRadius: 10, padding: "10px 13px",
                fontSize: 13, marginBottom: 14, lineHeight: 1.5,
              }}>
                {parseError}
              </div>
            )}

            {/* Source tabs */}
            <div style={{ display: "flex", gap: 8, marginBottom: 20 }}>
              {([
                { key: "bc" as Source, label: "Bean Conqueror" },
                { key: "csv" as Source, label: "CSV" },
                ...(llmEnabled ? [{ key: "paste" as Source, label: "Paste text" }] : []),
              ]).map(({ key, label }) => (
                <button
                  key={key}
                  onClick={() => setSource(key)}
                  className={source === key ? "btn btn-accent" : "btn btn-ghost"}
                  style={{ fontSize: 13, padding: "0 14px", height: 36, borderRadius: 10 }}
                >
                  {label}
                </button>
              ))}
            </div>

            {/* Bean Conqueror */}
            {source === "bc" && (
              <div>
                <p style={{ fontSize: 14.5, lineHeight: 1.6, color: "var(--ink-dim)", marginBottom: 16 }}>
                  Export your beans from Bean Conqueror: <strong>Settings → Backup &amp; Export → Export JSON</strong>. Then pick the file below.
                </p>
                <input
                  ref={fileRef}
                  type="file"
                  accept=".json"
                  onChange={handleFile}
                  style={{ display: "none" }}
                />
                <button
                  className="btn btn-accent"
                  onClick={() => fileRef.current?.click()}
                  disabled={phase === "parsing"}
                  style={{ width: "100%", height: 52 }}
                >
                  {phase === "parsing"
                    ? <><Icon name="bean" size={18} stroke={1.8} /> Reading file…</>
                    : <><Icon name="bean" size={18} stroke={1.8} /> Choose .json file</>}
                </button>
              </div>
            )}

            {/* CSV */}
            {source === "csv" && (
              <div>
                <p style={{ fontSize: 14.5, lineHeight: 1.6, color: "var(--ink-dim)", marginBottom: 14 }}>
                  No CSV yet? Ask ChatGPT or Claude to format your coffee list using this prompt:
                </p>

                {/* Prompt expander */}
                <button
                  onClick={() => setShowPrompt((v) => !v)}
                  style={{
                    display: "flex", alignItems: "center", gap: 6, width: "100%",
                    background: "var(--surface)", border: "1px solid var(--line)",
                    borderRadius: 10, padding: "9px 13px", cursor: "pointer",
                    color: "var(--ink-dim)", fontSize: 13, marginBottom: 10,
                  }}
                >
                  <Icon name="chev" size={13} stroke={2}
                    style={{ transform: showPrompt ? "rotate(90deg)" : "none", transition: "transform .15s ease" }} />
                  How to make this CSV
                </button>

                {showPrompt && (
                  <div style={{ marginBottom: 14, position: "relative" }}>
                    <pre style={{
                      background: "var(--surface)", border: "1px solid var(--line)",
                      borderRadius: 10, padding: "12px 13px", fontSize: 12,
                      whiteSpace: "pre-wrap", wordBreak: "break-word",
                      color: "var(--ink-dim)", lineHeight: 1.5,
                      maxHeight: 220, overflowY: "auto",
                    }}>
                      {IMPORT_PROMPT}
                    </pre>
                    <button
                      onClick={copyPrompt}
                      className="btn btn-ghost"
                      style={{
                        position: "absolute", top: 8, right: 8, height: 28,
                        padding: "0 10px", fontSize: 11.5, borderRadius: 7,
                      }}
                    >
                      {promptCopied ? "Copied!" : "Copy"}
                    </button>
                    <div className="label" style={{ marginTop: 8, color: "var(--ink-ghost)" }}>
                      Columns: <code style={{ fontSize: 11 }}>{CSV_COLUMNS}</code>
                    </div>
                    <div className="label" style={{ marginTop: 4, color: "var(--ink-ghost)" }}>
                      Example: <code style={{ fontSize: 11 }}>{CSV_EXAMPLE}</code>
                    </div>
                  </div>
                )}

                <input
                  ref={source === "csv" ? fileRef : undefined}
                  type="file"
                  accept=".csv"
                  onChange={handleFile}
                  style={{ display: "none" }}
                />
                <button
                  className="btn btn-accent"
                  onClick={() => fileRef.current?.click()}
                  disabled={phase === "parsing"}
                  style={{ width: "100%", height: 52 }}
                >
                  {phase === "parsing"
                    ? <><Icon name="scale" size={18} stroke={1.8} /> Reading file…</>
                    : <><Icon name="scale" size={18} stroke={1.8} /> Choose .csv file</>}
                </button>
              </div>
            )}

            {/* Paste text (LLM-powered) */}
            {source === "paste" && llmEnabled && (
              <div>
                <p style={{ fontSize: 14.5, lineHeight: 1.6, color: "var(--ink-dim)", marginBottom: 14 }}>
                  Paste any description of your coffees — a list, a spreadsheet paste, notes — and the AI will structure them.
                </p>
                <textarea
                  value={pasteText}
                  onChange={(e) => setPasteText(e.target.value)}
                  placeholder={"Koppi Ethiopia Guji, natural, light roast, ~200g\nFive Senses Kenya Kiambu, washed..."}
                  rows={6}
                  style={{
                    width: "100%", padding: "12px 13px", borderRadius: 12,
                    background: "var(--surface)", border: "1px solid var(--line)",
                    color: "var(--ink)", fontFamily: "var(--font-ui)", fontSize: 14,
                    resize: "vertical", outline: "none", boxSizing: "border-box",
                    marginBottom: 12,
                  }}
                />
                <button
                  className="btn btn-accent"
                  onClick={handleParse}
                  disabled={!pasteText.trim() || phase === "parsing"}
                  style={{ width: "100%", height: 52 }}
                >
                  {phase === "parsing"
                    ? <><Icon name="spark" size={18} stroke={1.8} /> Parsing…</>
                    : <><Icon name="spark" size={18} stroke={1.8} /> Parse with AI</>}
                </button>
              </div>
            )}
          </>
        )}

        {/* Review */}
        {phase === "review" && (
          <>
            <SheetHeader title={`Review ${rows.length} coffee${rows.length === 1 ? "" : "s"}`} onClose={handleClose} />

            {warnings.length > 0 && (
              <div style={{
                background: "var(--surface)", border: "1px solid var(--line)",
                borderRadius: 10, padding: "9px 12px", marginBottom: 12,
              }}>
                <div className="label" style={{ marginBottom: 4 }}>Warnings</div>
                {warnings.map((w, i) => (
                  <div key={i} style={{ fontSize: 12.5, color: "var(--ink-dim)", lineHeight: 1.4 }}>· {w}</div>
                ))}
              </div>
            )}

            {/* Select all / count */}
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
              <button
                onClick={toggleAll}
                style={{ background: "none", border: "none", cursor: "pointer", color: "var(--ink-dim)", fontSize: 13, padding: 0 }}
              >
                {included.size === rows.length ? "Deselect all" : "Select all"}
              </button>
              <span className="label">{included.size} of {rows.length} selected</span>
            </div>

            {rows.some((r) => r.isDuplicate) && (
              <div style={{ fontSize: 12.5, color: "var(--accent)", marginBottom: 10, lineHeight: 1.4 }}>
                Duplicates (matching roaster + name) are unchecked by default — include them if you want to keep them.
              </div>
            )}

            <div style={{ maxHeight: "44vh", overflowY: "auto" }}>
              {rows.map((r, i) => (
                <ReviewRow
                  key={i}
                  item={r}
                  included={included.has(i)}
                  onToggle={() => toggleRow(i)}
                  onChange={(patch) => updateRow(i, patch)}
                />
              ))}
            </div>

            <button
              className="btn btn-accent"
              onClick={handleCommit}
              disabled={included.size === 0}
              style={{ width: "100%", height: 52, marginTop: 14 }}
            >
              Import {included.size} coffee{included.size === 1 ? "" : "s"}
            </button>
          </>
        )}

        {/* Committing */}
        {phase === "committing" && (
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center", padding: "60px 20px" }}>
            <div className="shimmer" style={{ width: 48, height: 48, borderRadius: "50%", marginBottom: 16 }} />
            <div style={{ fontSize: 16, fontWeight: 600 }}>Saving coffees…</div>
          </div>
        )}

        {/* Done */}
        {phase === "done" && (
          <>
            <SheetHeader title="Done!" onClose={handleClose} />
            <EmptyState
              icon="shelf"
              title={`Imported ${importedCount} coffee${importedCount === 1 ? "" : "s"}`}
              body="Your shelf has been updated. Tasting-note colours will fill in shortly."
              iconSize={44}
              pad="40px 20px"
            />
            {warnings.length > 0 && (
              <div style={{ marginTop: 8 }}>
                <div className="label" style={{ marginBottom: 4 }}>{warnings.length} row{warnings.length === 1 ? "" : "s"} skipped</div>
                {warnings.map((w, i) => (
                  <div key={i} style={{ fontSize: 12.5, color: "var(--ink-dim)", lineHeight: 1.4 }}>· {w}</div>
                ))}
              </div>
            )}
            <button className="btn btn-ghost" onClick={handleClose} style={{ width: "100%", height: 48, marginTop: 20 }}>
              Close
            </button>
          </>
        )}
      </div>
    </Sheet>
  );
}
